import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    suspicious: "error",
    pedantic: "warn",
    perf: "error",
    style: "warn",
    restriction: "off",
    nursery: "warn",
  },
  ignorePatterns: ["*.config.ts", "node_modules"],
  plugins: [
    "eslint",
    "typescript",
    "unicorn",
    "react",
    "react-perf",
    "import",
    "jsx-a11y",
    "promise",
  ],
  rules: {
    "eslint/func-style": "off",
    "eslint/init-declarations": "warn",
    "eslint/no-implicit-coercion": ["error", { allow: ["!!"] }],
    "eslint/no-magic-numbers": ["warn", { ignore: [0, 1, -1] }],
    "eslint/no-ternary": "off",
    "eslint/sort-imports": "off",
    "eslint-plugin-import/group-exports": "off",
    "eslint-plugin-import/no-named-export": "off",
    "eslint-plugin-import/no-relative-parent-imports": "off",
    "eslint-plugin-import/prefer-default-export": "off",
    "eslint-plugin-import/unambiguous": "warn",
    "eslint-plugin-unicorn/filename-case": "off",
    "eslint-plugin-unicorn/no-null": "warn",
    "eslint-plugin-react/react-in-jsx-scope": "off",
    "import/no-default-export": "off",
    "import/no-unassigned-import": ["error", { allow: ["**/*.css"] }],
    "react-perf/jsx-no-new-function-as-prop": "warn",
    "react/jsx-filename-extension": "off",
    "react/jsx-max-depth": ["warn", { max: 6 }],
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
  },
});